### ISSUE TITLE
Uncaught Error: watch $ATOM_HOME/toolbar.cson ENOSPC

### ISSUE THREAD

**Issue by CodebitsDesign** [cakecatz/flex-toolbar#108]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: elementary OS
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package 0.12.0

### Stack Trace

Uncaught Error: watch /home/bike/.atom/toolbar.cson ENOSPC

```
At events.js:160

Error: watch /home/bike/.atom/toolbar.cson ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at createFsWatchInstance (/packages/flex-tool-bar/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/packages/flex-tool-bar/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/packages/flex-tool-bar/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/packages/flex-tool-bar/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at /packages/flex-tool-bar/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -0:28.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-nord-atom-syntax-accessibility-custom-comment-contrast.compact-tab-bar.use-animations.compact-tree-view.paint-cursor.theme-nord-atom-syntax.theme-atom-material-ui)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
advanced-open-file 0.16.6 
angular-2 0.2.6 
angular-2-typeScript-snippets 0.6.3 
angular2-snippets 0.3.0 
angular2-snippets-atom 0.7.0 
angularjs 0.4.0 
atom-beautify 0.29.23 
atom-copy-on-select 1.4.0 
atom-csv-markdown 1.0.2 
atom-electron-snippets 2.0.3 
atom-html-preview 0.1.22 
atom-jasmine-typescript 1.1.0 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.10 
atom-terminal 0.8.0 
atom-terminal-panel 4.4.4 
atom-ternjs 0.18.2 
atom-typescript 11.0.3 
atom-typescript-beta 11.0.1 
atom-yeoman 0.3.15 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
bootstrap-sass-snippets 2.1.1 
bottom-dock 0.4.4 
build-markdown 1.1.0 
busy-signal 1.4.1 
color-picker 2.2.5 
column-select 0.2.0 
css-snippets 1.1.0 
docblockr 0.9.4 
eclipse-keybindings 0.9.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.4 
flex-tool-bar 0.12.0 
font-viewer 0.3.1 
fonts 2.0.0 
git-clone 0.2.0 
git-control 0.9.0 
git-diff-details 1.4.0 
git-log 0.4.1 
git-plus 7.7.0 
git-projects 1.17.0 
git-status 0.3.4 
git-time-machine 1.5.9 
gitignore-snippets 0.2.5 
gulp-manager 0.2.19 
highlight-selected 0.13.1 
indent-guide-improved 1.4.12 
intentions 1.1.2 
javascript-snippets 1.2.1 
jumpy 3.1.3 
language-apache 1.7.0 
language-babel 2.57.7 
language-docker 1.1.7 
language-log 1.8.0 
language-markdown 0.21.0 
language-vala-modern 0.3.2 
last-cursor-position 0.9.2 
linter 2.1.4 
linter-csslint 1.3.4 
linter-eslint 8.1.7 
linter-htmlhint 1.3.3 
linter-jsonlint 1.3.0 
linter-markdown 4.0.0 
linter-scss-lint 3.1.0 
linter-tslint 1.3.0 
linter-ui-default 1.2.3 
markdown-image-helper 1.0.4 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.9 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
markdown-writer 2.6.4 
minimap 4.28.1 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
nuclide 0.220.0 
open-in-browser 0.5.0 
pdf-view 0.57.0 
php-twig 4.0.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
pretty-json 1.6.3 
project-manager 3.3.4 
project-plus 0.9.0 
remote-edit 1.9.0 
Remote-FTP 0.10.7 
run-in-terminal 1.0.0 
sass-autocompile 0.13.3 
script 3.14.1 
split-diff 1.3.0 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.1 
tidy-markdown 3.0.1 
todo-show 1.11.0 
tomorrow-night-eighties-syntax 1.0.2 
tool-bar 1.1.0 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.3.1 
v-bootstrap4 0.1.8 
vim-mode-plus 0.91.0 
zentabs 0.8.8 
```

**Comment by Hativ3** [comment]
See https://github.com/atom/atom/issues/2082

Solution: https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#typeerror-unable-to-watch-path

**Comment by UziTech** [comment]
Closing as stale.

If this is still an issue feel free to let us know.
