### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by morita-hiroyuki1007** [cakecatz/flex-toolbar#109]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package 0.12.0

### Stack Trace

Uncaught TypeError: Cannot read property 'style' of null

```
At /Users/morita/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:175

TypeError: Cannot read property 'style' of null
    at Object.unfixToolBarHeight (/packages/flex-tool-bar/lib/flex-tool-bar.coffee:175:30)
    at Object.reloadToolbar (/packages/flex-tool-bar/lib/flex-tool-bar.coffee:167:8)
    at /packages/flex-tool-bar/lib/flex-tool-bar.coffee:115:10
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.activateItem (/app.asar/src/pane.js:452:21)
    at TabBarView.module.exports.TabBarView.onMouseDown (/app.asar/node_modules/tabs/lib/tab-bar-view.js:678:19)
```

### Commands

```
     -6:58.2.0 application:new-file (input.hidden-input)
     -6:51.8.0 application:add-project-folder (input.hidden-input)
     -6:42.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -6:30.1.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -5:41.9.0 core:confirm (input.hidden-input)
     -4:47.9.0 project-find:show (div.package-detail.panels-item)
     -4:45.5.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -3:14.9.0 encoding-selector:show (atom-text-editor.editor)
     -3:12.4.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -3:10.2.0 core:confirm (input.hidden-input)
     -2:56.8.0 core:paste (input.hidden-input)
  5x -2:55.4.0 core:backspace (input.hidden-input)
     -2:54.4.0 core:confirm (input.hidden-input)
     -2:44.3.0 core:backspace (input.hidden-input)
     -2:44.1.0 core:confirm (input.hidden-input)
     -1:57.3.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
an-color-picker 1.0.2 
atom-beautify 0.29.24 
atom-html-preview 0.1.22 
atom-minify 0.8.0 
atom-terminal-panel 4.4.4 
atom-ternjs 0.18.3 
auto-indent 0.5.0 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
emmet 2.4.3 
file-icons 2.1.4 
flex-tool-bar 0.12.0 
japanese-menu 1.12.0 
pigments 0.39.1 
sass-autocompile 0.13.3 
tag 0.5.0 
tool-bar 1.1.0 
```

**Comment by UziTech** [comment]
Closing as stale.

If this is still an issue feel free to let us know.
