### ISSUE TITLE
Uncaught TypeError: q.drain is not a function

### ISSUE THREAD

**Issue by fermuso** [cakecatz/flex-toolbar#117]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package 0.12.0

### Stack Trace

Uncaught TypeError: q.drain is not a function

```
At C:\Users\71128300H\.atom\packages\flex-tool-bar\node_modules\async\lib\async.js:909

TypeError: q.drain is not a function
    at /packages/flex-tool-bar/node_modules/async/lib/async.js:909:23
    at /packages/flex-tool-bar/node_modules/async/lib/async.js:44:16
    at /packages/flex-tool-bar/node_modules/fs-plus/lib/fs-plus.js:438:24
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -0:35.1.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:34.1.0 core:paste (input.hidden-input)
     -0:33.2.0 core:confirm (input.hidden-input)
     -0:22.5.0 remote-sync:upload-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
autocomplete-python 1.10.2 
block-comment-plus 0.5.1 
file-icons 2.1.11 
flex-tool-bar 0.12.0 
git-change-marker 0.13.0 
git-control 0.9.0 
git-log 0.4.1 
git-plus 7.9.3 
git-split-diff-hyperclick 0.3.12 
git-time-machine 1.5.9 
hyperclick 0.1.5 
language-ansible 0.2.1 
merge-conflicts 1.4.5 
open-recent 5.0.0 
platformio-ide-terminal 2.6.0 
project-manager 3.3.5 
python-indent 1.1.0 
python-snippets 1.9.0 
remote-sync 4.1.5 
split-diff 1.5.1 
tool-bar 1.1.0 
tree-view-git-status 1.4.0 
```

**Comment by UziTech** [comment]
Closing as stale.

If this is still an issue feel free to let us know.
