### ISSUE TITLE
Failed to load the flex-tool-bar package

### ISSUE THREAD

**Issue by oezguensi** [cakecatz/flex-toolbar#134]
[Enter steps to reproduce:]

1. Update to 0.16.0

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.2
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package 0.16.0

### Stack Trace

Failed to load the flex-tool-bar package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/flex-tool-bar/node_modules/fs-plus/lib/fs-plus.js:11:7)
    at /packages/flex-tool-bar/node_modules/fs-plus/lib/fs-plus.js:721:4)
    at /packages/flex-tool-bar/node_modules/fs-plus/lib/fs-plus.js:723:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/flex-tool-bar/lib/flex-tool-bar.coffee:3:6)
    at /packages/flex-tool-bar/lib/flex-tool-bar.coffee:1:1)
    at /packages/flex-tool-bar/lib/flex-tool-bar.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:529:23)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:818:27)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-clock 0.1.16 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-modules 1.11.0 
autocomplete-paths 2.12.2 
clickable-npm-scripts 3.9.0 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.16 
flex-tool-bar 0.16.0 
git-plus 7.10.0 
git-plus-toolbar 1.0.1 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
hyperclick 0.1.5 
js-hyperclick 1.13.0 
language-babel 2.84.0 
local-history 4.3.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.0 
project-manager 3.3.5 
react 0.17.0 
Sublime-Style-Column-Selection 1.7.4 
todo-show 2.1.0 
tool-bar 1.1.6 
tool-bar-atom 1.7.0 
tree-view-copy-relative-path 1.2.0 
```

UPDATE: Solved problem by doing:
1) Delete package
2) Delete /.atom/compile-cach
3) Restart Atom
4) Reinstall package

**Comment by UziTech** [comment]
seems like an Atom or NPM issue
