### ISSUE TITLE
function call in toolbar.js not work ?

### ISSUE THREAD

**Issue by faildproject** [cakecatz/flex-toolbar#142]
Hello,

when I try to use the Examples from Readme I get some Errors:

Example:

```
module.exports = [
	{
		type: "button",
		icon: "gear",
		callback: "flex-tool-bar:edit-config-file",
		tooltip: "Edit Tool Bar"
	},
	{
    type: "function",
    icon: "bug",
    callback: (target) -> console.dir target,
    tooltip: "Debug Target"
	},
        {
		type: "button",
		callback: "core:save",
		tooltip: "Save",
		icon: "floppy-o",
		iconset: "fa",
		show: {
			 function: (editor) -> editor.isModified()
		}
          }

];
```
**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package 2.0.0

### Stack Trace

Uncaught SyntaxError: Unexpected token >

```
At C:\Users\Privat\.atom\packages\flex-tool-bar\lib\flex-tool-bar.js:440

SyntaxError: Unexpected token >
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.25.0/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.25.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.25.0/resources/app/src/native-compile-cache.js:66:33)
    at Object.loadConfig (/packages/flex-tool-bar/lib/flex-tool-bar.js:590:15)
    at Object.reloadToolbar (/packages/flex-tool-bar/lib/flex-tool-bar.js:430:32)
    at /packages/flex-tool-bar/lib/flex-tool-bar.js:377:9)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:194:7)
    at /packages/flex-tool-bar/node_modules/chokidar/index.js:199:15)
    at FSWatcher._emit (/packages/flex-tool-bar/node_modules/chokidar/index.js:241:5)
    at /packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:263:16)
    at FSReqWrap.oncomplete (fs.js:114:15)
```

I think it is an issue by myself, because Unexpected token Error? Can everyone help me? 
I allways tryed to use 'function-call' or "function-call"

Thanks

**Comment by UziTech** [comment]
The examples are written for coffee script so you will need to use a `.coffee` config file

**Comment by UziTech** [comment]
Or you can change

```
(target) -> console.dir target
```

to

```
(target) => console.dir target
```

so it is valid javascript

**Comment by faildproject** [comment]
Thank you :)
