### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by andrewbihl** [cakecatz/flex-toolbar#144]
[Enter steps to reproduce:]

1. Edit config file based on [instructional found here.](https://atom.io/themes/atom-visual-studio-code-ui)
2. Save file
3. This error appears.

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package 2.0.0

### Stack Trace

Uncaught SyntaxError: Unexpected identifier

```
At /Users/andrewbihl/.atom/packages/flex-tool-bar/lib/flex-tool-bar.js:440

SyntaxError: Unexpected identifier
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.loadConfig (/packages/flex-tool-bar/lib/flex-tool-bar.js:590:15)
    at Object.reloadToolbar (/packages/flex-tool-bar/lib/flex-tool-bar.js:430:32)
    at /packages/flex-tool-bar/lib/flex-tool-bar.js:377:9)
    at emitOne (events.js:96:13)
    at FSWatcher.emit (events.js:191:7)
    at /packages/flex-tool-bar/node_modules/chokidar/index.js:199:15)
    at FSWatcher._emit (/packages/flex-tool-bar/node_modules/chokidar/index.js:241:5)
    at /packages/flex-tool-bar/node_modules/chokidar/lib/fsevents-handler.js:206:14)
    at addOrChange (/packages/flex-tool-bar/node_modules/chokidar/lib/fsevents-handler.js:212:7)
    at /packages/flex-tool-bar/node_modules/chokidar/lib/fsevents-handler.js:244:16)
    at filteredListener (/packages/flex-tool-bar/node_modules/chokidar/lib/fsevents-handler.js:60:7)
    at /packages/flex-tool-bar/node_modules/chokidar/lib/fsevents-handler.js:85:11
    at Array.forEach (native)
    at /packages/flex-tool-bar/node_modules/chokidar/lib/fsevents-handler.js:84:34)
    at emitThree (events.js:116:13)
    at FSEvents.emit (events.js:197:7)
    at /packages/flex-tool-bar/node_modules/fsevents/fsevents.js:47:11)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

### Commands

```
     -0:35.4.0 application:add-project-folder (input.hidden-input)
     -0:33.3.0 command-palette:toggle (input.hidden-input)
     -0:30.6.0 core:confirm (input.hidden-input)
     -0:30.6.0 flex-tool-bar:edit-config-file (input.hidden-input)
     -0:28.8.0 core:select-all (input.hidden-input)
     -0:28.5.0 core:backspace (input.hidden-input)
     -0:28.2.0 core:paste (input.hidden-input)
  2x -0:27.4.0 core:save (input.hidden-input)
     -0:13.3.0 application:add-project-folder (input.hidden-input)
     -0:11.5.0 command-palette:toggle (input.hidden-input)
     -0:09.0 core:move-down (input.hidden-input)
     -0:07.3.0 core:move-up (input.hidden-input)
     -0:06.9.0 core:confirm (input.hidden-input)
     -0:06.9.0 flex-tool-bar:edit-config-file (input.hidden-input)
  2x -0:06.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-visual-studio-code-ui 1.3.4 
autocomplete-clang 0.11.4 
dbg 1.6.3 
dbg-gdb 1.7.8 
flex-tool-bar 2.0.0 
language-babel 2.84.0 
language-docker 1.1.8 
language-mips 0.3.0 
linter-gcc 0.7.1 
minimap 4.29.8 
output-panel 0.3.4 
platformio-ide-terminal 2.8.1 
pretty-json 2.0.0 
tool-bar 1.1.7 
```

**Comment by UziTech** [comment]
is your toolbar config file a .coffee file?
