### ISSUE TITLE
Uncaught TypeError: toolBarButtons is not iterable

### ISSUE THREAD

**Issue by RusDangerMaster** [cakecatz/flex-toolbar#153]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package 2.1.1

### Stack Trace

Uncaught TypeError: toolBarButtons is not iterable

```
At C:\Users\Вероника\.atom\packages\flex-tool-bar\lib\flex-tool-bar.js:451

TypeError: toolBarButtons is not iterable
    at Object.addButtons (/packages/flex-tool-bar/lib/flex-tool-bar.js:482:21)
    at Object.reloadToolbar (/packages/flex-tool-bar/lib/flex-tool-bar.js:443:9)
    at Object.onDidChangeItem (/packages/flex-tool-bar/lib/flex-tool-bar.js:366:8)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.29.0/resources/app/src/workspace.js:443:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.29.0/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane-container.js:285:26)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane.js:444:48)
    at Pane.activateItem (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane.js:583:18)
    at TabBarView.module.exports.TabBarView.onClick (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:730:25)
```

### Commands

```
     -2:32.3.0 find-and-replace:show (div.package-detail.panels-item)
     -2:32.1.0 core:paste (input.hidden-input)
  6x -1:59.1.0 core:close (div.markdown-preview)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
auto-encoding 0.7.1 
autocomplete-date 0.4.0 
autocomplete-math 0.1.1 
autocomplete-modules 2.1.0 
autocomplete-sql 0.5.0 
emmet 2.4.3 
export-html 3.1.0 
file-icons 2.1.22 
flex-tool-bar 2.1.1 
highlight-selected 0.14.0 
language-qml 1.0.0 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
multi-cursor 2.1.5 
multi-wrap-guide 1.1.5 
open-in-browsers 0.0.30 
open-recent 5.0.0 
pane-layout-plus 0.7.4 
pdf-view 0.70.0 
pigments 0.40.2 
simple-drag-drop-text 0.4.0 
sort-lines 0.18.0 
split-diff 1.5.2 
svg-preview 0.12.1 
tool-bar 1.1.7 
```

**Comment by UziTech** [comment]
What is your toolbar configuration?

**Comment by UziTech** [comment]
I added extra error handling in [v2.1.2](https://github.com/cakecatz/flex-toolbar/compare/v2.1.1...v2.1.2)

If that doesn't work we can reopen this issue.
