### ISSUE TITLE
Uncaught TypeError: url.startsWith is not a function

### ISSUE THREAD

**Issue by betonajera9** [cakecatz/flex-toolbar#160]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 19.04
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package 2.1.4

### Stack Trace

Uncaught TypeError: url.startsWith is not a function

```
At /home/betonajera/.atom/packages/flex-tool-bar/lib/types/url.js:19

TypeError: url.startsWith is not a function
    at ToolBarButtonView.callback (/packages/flex-tool-bar/lib/types/url.js:19:12)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:140:16)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:113:12)
```

### Commands

```
     -4:21.3.0 core:undo (input.hidden-input)
     -4:00.4.0 core:move-right (input.hidden-input)
     -3:59.9.0 editor:newline (input.hidden-input)
  2x -2:06.1.0 intentions:highlight (input.hidden-input)
     -2:03.5.0 core:paste (input.hidden-input)
     -2:02.0 core:save (input.hidden-input)
     -1:55.3.0 editor:newline (input.hidden-input)
     -1:00.0 intentions:highlight (input.hidden-input)
     -0:59.7.0 core:save (input.hidden-input)
     -0:50.6.0 intentions:highlight (input.hidden-input)
     -0:50.4.0 core:save (input.hidden-input)
     -0:49 core:delete (input.hidden-input)
     -0:48.5.0 intentions:highlight (input.hidden-input)
     -0:48.4.0 core:save (input.hidden-input)
  2x -0:33.4.0 editor:newline (input.hidden-input)
     -0:30 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Non-Core Packages

```
atom-2048 3.1.0 
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-live-server 2.3.0 
atom-material-ui 2.1.3 
atom-ternjs 0.20.0 
autocomplete-clang 0.12.0 
build 0.70.0 
busy-signal 2.0.1 
color-picker 2.3.0 
docker 0.8.0 
emmet 2.4.3 
emmet-jsx-props 1.4.0 
file-icons 2.1.35 
firacode 0.3.0 
flex-tool-bar 2.1.4 
git-time-machine 2.1.0 
highlight-selected 0.16.0 
hyperclick 0.1.5 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-ini 1.21.0 
linter 2.3.1 
linter-csslint 2.0.6 
linter-gcc 0.7.1 
linter-jscs 4.2.2 
linter-jsonlint 1.4.0 
linter-php 1.6.1 
linter-ui-default 1.8.0 
linter-write-good 0.9.2 
logo-file-icons 1.13.0 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
minimap-selection 4.5.0 
open-in-browsers 0.0.30 
pigments 0.40.2 
platformio-ide-terminal 2.9.4 
Quick-JavaScript 2.2.0 
rest-client 1.3.1 
script 3.18.1 
seti-syntax 1.2.0 
split-diff 1.6.0 
teletype 0.13.4 
todo-show 2.3.2 
tool-bar 1.1.12 
```

**Comment by UziTech** [comment]
Can you provide your configuration file?
