### ISSUE TITLE
flex-toolbar fails to load

### ISSUE THREAD

**Issue by tashyama** [cakecatz/flex-toolbar#165]
I am seeing the following error during Atom startup. Atom Version is  1.26.1.

TypeError: (0 , _util.promisify) is not a function
    at /home/ANT.AMAZON.COM/ashyama/.atom/packages/flex-tool-bar/node_modules/sb-fs/lib/index.js:17:46
    at Array.forEach (native)
    at Object.<anonymous> (/home/ANT.AMAZON.COM/ashyama/.atom/packages/flex-tool-bar/node_modules/sb-fs/lib/index.js:13:26)
    at Object.<anonymous> (/home/ANT.AMAZON.COM/ashyama/.atom/packages/flex-tool-bar/node_modules/sb-fs/lib/index.js:51:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///opt/atom/resources/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/ANT.AMAZON.COM/ashyama/.atom/packages/flex-tool-bar/node_modules/atom-package-deps/lib/helpers.js:10:36)
    at Object.<anonymous> (/home/ANT.AMAZON.COM/ashyama/.atom/packages/flex-tool-bar/node_modules/atom-package-deps/lib/helpers.js:196:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///opt/atom/resources/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/ANT.AMAZON.COM/ashyama/.atom/packages/flex-tool-bar/node_modules/atom-package-deps/lib/index.js:10:39)
    at Object.<anonymous> (/home/ANT.AMAZON.COM/ashyama/.atom/packages/flex-tool-bar/node_modules/atom-package-deps/lib/index.js:55:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///opt/atom/resources/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/home/ANT.AMAZON.COM/ashyama/.atom/packages/flex-tool-bar/lib/flex-tool-bar.js:67:3)

**Comment by UziTech** [comment]
Why are you setting up Atom v1.26.1? That version is over a year old.

Based on your stack trace it uses an old version of node that doesn't have `util.promisify`

**Comment by tashyama** [comment]
I see, It just happened to be the version that Ubuntu downloader vended out.

Which version do you suggest?

**Comment by UziTech** [comment]
v1.41.0 is the latest stable version
