### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by fojt-cz** [cakecatz/flex-toolbar#28]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package, v0.4.2

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At C:\Users\martin\.atom\packages\flex-tool-bar\lib\flex-tool-bar.coffee:156

TypeError: Cannot read property 'name' of undefined
  at Object.module.exports.storeGrammar (C:\Users\martin\.atom\packages\flex-tool-bar\lib\flex-tool-bar.coffee:156:37)
  at C:\Users\martin\.atom\packages\flex-tool-bar\lib\flex-tool-bar.coffee:34:11
  at Emitter.module.exports.Emitter.emit (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\src\pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\src\pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\src\pane.js:298:21)
  at tabs-tab.<anonymous> (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\martin\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -0:45.9.0 settings-view:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "SFTP-deployment",
      "ctags-status",
      "tree-view-open-files",
      "Remote-FTP",
      "coffee-compiler",
      "git-plus",
      "sass-compiler",
      "remote-sync",
      "example",
      "language-smarty"
    ]
  },
  "flex-tool-bar": {}
}
```

### Installed Packages

```coffee
# User
file-icons, v1.5.8
flex-tool-bar, v0.4.2
language-smarty-php, v0.5.0
less-compiler, v0.6.2
linter, vundefined
open-recent, v2.2.4
php-class-tree, vundefined
project-manager, v1.15.10
project-view, v0.1.2
sass-autocompile, v0.7.1
symbols-tree-view, v0.9.3
tool-bar, v0.1.8
tool-bar-main, v0.0.8
tree-view-finder, v0.2.1
tree-view-git-status, v0.1.1

# Dev
No dev packages
```

**Comment by cakecatz** [comment]
I couldn't produce this :cry:

**Comment by fojt-cz** [comment]
me too, i had not this problem after restart

**Comment by cakecatz** [comment]
@fojt-cz hmm...
If happens again, please reopen this issue.
