### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by onetrev** [cakecatz/flex-toolbar#53]
Not 100% sure what is causing this.... But here goes...

1. Open Atom
2. Click on any toolbar item below a certain point, in my case about 6 icons down from the top and boom this error is thrown when clicking on all icons below that point.

**Atom Version**: 1.3.1
**System**: Microsoft Windows 10 Home
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package, v0.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /C:/Users/Trevor/.atom/packages/flex-tool-bar/types/button.coffee:14

TypeError: Cannot read property 'length' of undefined
    at Object.options.callback (file:///C:/Users/Trevor/.atom/packages/flex-tool-bar/types/button.coffee:10:7)
    at space-pen-button.<anonymous> (C:\Users\Trevor\.atom\packages\tool-bar\lib\tool-bar-button-view.coffee:44:30)
    at space-pen-button.jQuery.event.dispatch (C:\Users\Trevor\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-button.elemData.handle (C:\Users\Trevor\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-fusion-syntax"
    ],
    "ignoredNames": [
      "*.sql"
    ],
    "audioBeep": false,
    "autoHideMenuBar": true
  },
  "flex-tool-bar": {
    "showConfigButton": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
atom-css-unit-converter, v1.0.1
atom-dark-fusion-syntax, v1.1.0
clipboard-plus, v0.5.1
docblockr, v0.7.3
emmet, v2.3.17
file-icons, v1.6.13
flex-tool-bar, v0.7.0
imdone-atom, v1.3.11
linter, v1.11.3
linter-jshint, v1.2.1
linter-php, v1.1.6
minimap, v4.17.0
nucleus-dark-ui, v0.6.14
package-sync, v0.2.0
pigments, v0.19.2
project-manager, v2.6.5
symbol-gen, v1.0.0
tool-bar, v0.1.9
wordpress-dictionary, v4.3.7

# Dev
No dev packages
```

**Comment by cakecatz** [comment]
@onetrev Thanks for reporting.
Could you show your toolbar.cson (or json, json5) ?

**Comment by onetrev** [comment]
Absolutely. Here it is....

```
[
  {
    "type": "button",
    "icon": "archive",
    "callback": "window:save-all",
    "tooltip": "Save All Open Windows",
    "iconset": "ion"
  },
  {
    "type": "button",
    "icon": "embed",
    "callback": "emmet:wrap-with-abbreviation",
    "tooltip": "Emmet Wrap",
    "iconset": "icomoon"
  },
  {
    "type": "button",
    "icon": "embed2",
    "callback": "emmet:interactive-expand-abbreviation",
    "tooltip": "Interactive Emmet Wrap",
    "iconset": "icomoon"
  },
  {
    "type": "button",
    "icon": "indent-more",
    "callback": "editor:auto-indent",
    "tooltip": "Auto Indent",
    "iconset": "fi"
  },
  {
    "type": "button",
    "icon": "map",
    "callback": "symbols-view:toggle-file-symbols",
    "tooltip": "File Symbols",
    "iconset":"ion"
  },
  {
    "type": "button",
    "icon": "android-color-palette",
    "callback": "pigments:show-palette",
    "tooltip": "Pigments",
    "iconset":"ion"
  },
  {
    "type": "button",
    "icon": "bookmark",
    "callback": "bookmarks:toggle-bookmark",
    "tooltip": "Toggle Bookmark",
    "iconset":"ion"
  },
  {
    "type": "button",
    "icon": "check-square-o",
    "callback": "imdone-atom:tasks",
    "tooltip": "Project To Do List",
    "iconset":"fa"
  },
  {
    "type": "button",
    "icon": "circuit-board",
    "callback": "git-diff:toggle-diff-list",
    "tooltip": "Git Diffs",
  },
  {
    "type": "spacer"
  },
  {
    "type": "button",
    "icon": "three-bars",
    "tooltip": "Toggle Command Palette"
    "callback": ["command-palette:toggle"]
  },
  {
    "type": "button",
    "icon": "file-submodule",
    "tooltip": "Toggle Projects"
    "callback": ["project-manager:list-projects"]
  },
  {
    "type": "url",
    "icon": "wordpress-plain",
    "url": "https://codex.wordpress.org/Function_Reference",
    "iconset": "devicon"
  },
  {
    "type": "button",
    "icon": "search",
    "iconset": "ion",
    "tooltip": "Find in Project"
    "callback": ["project-find:show"]
  },
  {
    "type": "button",
    "icon": "bug",
    "tooltip": "Toggle Dev Tools"
    "callback": ["window:toggle-dev-tools"]
  },
  {
    "type": "button",
    "icon": "markdown",
    "callback": "markdown-preview:toggle",
    "hide": "!markdown"
  },
  {
    "type": "button",
    "icon": "document",
    "callback": "application:new-file",
    "tooltip": "New File",
    "iconset": "ion",
    "mode": "dev"
  },
  {
    "type": "button",
    "icon": "refresh",
    "callback": "window:reload",
    "tooltip": "Reload Window",
    "iconset": "ion",
    "mode": "dev"
  },
  {
    "type": "spacer"
  },
  {
    "type": "button",
    "icon": "gear-a",
    "callback": ["settings-view:open"],
    "iconset": "ion"
  }
]
```

**Comment by onetrev** [comment]
Just installed latest version. All fixed! Good stuff. Thank you!
