### ISSUE TITLE
Cannot find module 'mkdirp'

### ISSUE THREAD

**Issue by Chris92de** [cakecatz/flex-toolbar#64]
Steps to reproduce:
1. ... Install flex-tool-bar
2. ... Restart Atom

**Atom Version**: 1.5.4
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package, v0.8.1

### Stack Trace

Failed to load the flex-tool-bar package

```
At Cannot find module 'mkdirp'

Error: Cannot find module 'mkdirp'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Chris92\.atom\packages\flex-tool-bar\node_modules\fs-plus\lib\fs-plus.js:15:12)
    at Object.<anonymous> (C:\Users\Chris92\.atom\packages\flex-tool-bar\node_modules\fs-plus\lib\fs-plus.js:646:4)
    at Module._compile (C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Chris92/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:2:6)
    at Object.<anonymous> (file:///C:/Users/Chris92/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:1:1)
    at Module._compile (C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:720:27)
    at C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:116:28
    at Package.module.exports.Package.measure (C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\atom-environment.js:684:21)
    at module.exports (C:\Users\Chris92\AppData\Local\atom\app-1.5.4\resources\app.asar\src\initialize-application-window.js:28:10)
    at setupWindow (file:///C:/Users/Chris92/AppData/Local/atom/app-1.5.4/resources/app.asar/static/index.js:86:5)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autoflow",
      "tool-bar-main"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "flex-tool-bar": {}
}
```

### Installed Packages

```coffee
# User
achievements, v0.9.0
atom-material-syntax, v0.4.3
atom-material-ui, v1.2.7
color-picker, v2.1.1
flex-tool-bar, v0.8.1
minimap, v4.21.0
minimap-pigments, v0.2.0
pigments, v0.24.5
project-manager, v2.7.6
tool-bar, v0.3.0
tool-bar-almighty, v0.6.1

# Dev
No dev packages
```

**Comment by jerone** [comment]
Are you sure installation of Flex Tool Bar succeeded correctly? Because this package doesn't have a direct dependency for mkdirp: https://github.com/cakecatz/flex-toolbar/blob/master/package.json#L16-L22

**Comment by Chris92de** [comment]
It's weird, I uninstalled and reinstalled the plugin again, now it works flawlessly. No idea why my atom was spewing errors :/

**Comment by jerone** [comment]
Sometimes installation doesn't work perfectly. Luckily you solved it.
