### ISSUE TITLE
Cannot read property 'getGrammer' of undefined

### ISSUE THREAD

**Issue by UziTech** [cakecatz/flex-toolbar#78]
[Enter steps to reproduce below:]
1. Open atom

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package, v0.10.1
### Stack Trace

Failed to activate the flex-tool-bar package

```
At Cannot read property 'getGrammar' of undefined

TypeError: Cannot read property 'getGrammar' of undefined
    at Object.module.exports.storeGrammar (file:///C:/Users/tjbrix/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:289:29)
    at Object.module.exports.activate (file:///C:/Users/tjbrix/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:36:6)
    at Package.module.exports.Package.activateNow (C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\tjbrix\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "command-executor",
      "linter-tidy",
      "linter-csslint",
      "git-diff-details",
      "emmet-snippets-compatibility",
      "jsformat",
      "php-integrator-symbol-viewer",
      "semanticolor"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "git-time-machine",
      "atom-beautify",
      "sass-autocompile",
      "linter",
      "hyperclick",
      "git-control",
      "emmet",
      "git-diff-details",
      "keybinding-cheatsheet",
      "bottom-dock",
      "linter-manager",
      "php-cs-fixer",
      "split-diff",
      "activate-power-mode",
      "grammar-selector",
      "markdown-preview",
      "highlight-selected",
      "change-case",
      "node-debugger"
    ]
  },
  "flex-tool-bar": {}
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.5.2
atom-jasmine, v0.8.1
atomic-chrome, v0.3.0
auto-detect-indentation, v1.1.0
auto-indent, v0.5.0
autoclose-html, v0.23.0
autocomplete-html-entities, v0.1.0
autocomplete-json, v5.0.3
cursor-history, v0.5.9
docblockr, v0.7.3
double-tag, v0.2.0
emmet, v2.4.3
file-icons, v1.7.14
file-types, v0.5.1
flex-tool-bar, v0.10.1
highlight-selected, v0.11.2
hyperclick, v0.0.36
hyperclick-php, v0.2.1
hyperlink-hyperclick, v1.3.3
js-hyperclick, v1.4.2
language-babel, v2.28.0
language-batch, v0.3.3
language-ini, v1.16.0
line-diff-details, v1.3.5
line-ending-converter, v1.3.2
linter, v1.11.10
linter-coffeelint, v1.1.2
linter-eslint, v7.2.2
linter-htmlhint, v1.2.0
linter-js-yaml, v1.2.5
linter-markdown, v1.5.2
linter-phpcs, v1.4.0
linter-sass-lint, v1.5.0
merge-conflicts, v1.4.4
minimap, v4.24.6
minimap-bookmarks, v0.3.1
minimap-cursorline, v0.2.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-hide, v0.3.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.1
minimap-selection, v4.4.0
minimap-split-diff, v0.3.1
node-debugger, v1.7.0
open_in_cmd, v0.6.1
php-debug, v0.2.3
php-integrator-annotations, v0.4.1
php-integrator-autocomplete-plus, v0.8.1
php-integrator-base, v0.9.3
php-integrator-call-tips, v0.2.4
php-integrator-linter, v0.3.0
php-integrator-navigation, v0.7.1
php-integrator-tooltips, v0.6.1
pigments, v0.29.2
platformio-ide-terminal, v2.0.10
process-palette, v0.8.1
project-manager, v2.9.7
react, v0.15.0
Remote-FTP, v0.8.3
rest-client, v1.1.1
sass-autocompile, v0.12.7
Sublime-Style-Column-Selection, v1.5.1
tabasco, v0.5.0
tabs-to-spaces, v1.0.2
text-manipulation, v0.6.0
tool-bar, v0.4.0
trailing-spaces, v0.3.2
tree-view-git-status, v1.0.0

# Dev
No dev packages
```

**Comment by UziTech** [comment]
happens when openning atom on a new folder so no files are open initially
