### ISSUE TITLE
Uncaught TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by ch00d4** [cakecatz/flex-toolbar#87]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Debian GNU/Linux
**Thrown From**: [flex-tool-bar](https://github.com/cakecatz/flex-toolbar) package, v0.11.0
### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At /home/ch00d4/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:171

TypeError: Cannot read property 'element' of undefined
  at Object.module.exports.unfixToolBarHeight (/home/ch00d4/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:171:21)
  at Object.module.exports.reloadToolbar (/home/ch00d4/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:163:8)
  at Object.module.exports.consumeToolBar (/home/ch00d4/.atom/packages/flex-tool-bar/lib/flex-tool-bar.coffee:151:6)
  at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
  at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)

```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.5 (inactive)
atom-beautify, v0.29.13 (inactive)
atom-jshint, v2.0.0 (inactive)
auto-detect-indentation, v1.3.0 (inactive)
autocomplete-modules, v1.6.7 (inactive)
docblockr, v0.8.7 (inactive)
emmet, v2.4.3 (inactive)
flex-tool-bar, v0.11.0 (inactive)
sync-settings, v0.7.2 (inactive)
tool-bar, v1.0.1 (inactive)
toolbar-ide, v1.1.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.59.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by jerone** [comment]
Possible solution https://github.com/jerone/flex-toolbar/commit/770dc9d6093414f8a06fe881062649f7cb2ca15e

/cc @cakecatz

**Comment by cakecatz** [comment]
@jerone Good 👍 
Could you open PR?

**Comment by ClydeKuo** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [tool-bar](https://github.com/suda/tool-bar) package 1.0.1


### Stack Trace

Failed to activate the tool-bar package

```
At Cannot read property 'element' of undefined

TypeError: Cannot read property 'element' of undefined
  at Object.unfixToolBarHeight (/packages/flex-toolbar/lib/flex-tool-bar.coffee:171:21)
  at Object.reloadToolbar (/packages/flex-toolbar/lib/flex-tool-bar.coffee:163:8)
  at Object.consumeToolBar (/packages/flex-toolbar/lib/flex-tool-bar.coffee:151:6)
  at Provider.module.exports.Provider.provide (/app.asar/node_modules/service-hub/lib/provider.js:29:52)
  at ServiceHub.module.exports.ServiceHub.provide (/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
  at Package.module.exports.Package.activateServices (/app.asar/src/package.js:396:71)
  at Package.module.exports.Package.activateNow (/app.asar/src/package.js:221:16)
  at /app.asar/src/package.js:190:32
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at /app.asar/src/package.js:183:26
  at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
  at /app.asar/src/package-manager.js:352:19
  at /app.asar/src/config.js:635:20
  at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
  at Config.module.exports.Config.setRawValue (/app.asar/src/config.js:612:19)
  at Config.module.exports.Config.set (/app.asar/src/config.js:227:14)
  at Config.module.exports.Config.removeAtKeyPath (/app.asar/src/config.js:377:12)
  at Package.module.exports.Package.enable (/app.asar/src/package.js:81:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/app.asar/src/package-manager.js:173:14)
  at /app.asar/node_modules/settings-view/lib/package-card.js:348:27)
  at HTMLButtonElement.dispatch (/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 1.3.0 
atom-beautify 0.29.13 
atom-ctags 5.0.0 
simplified-chinese-menu 3.5.0 
atom-ternjs 0.16.1 
tree-view-git-status 1.3.1 
language-vue 0.21.2 
autocomplete-paths 1.0.2 
emmet 2.4.3 
file-icons 1.7.25 
flex-tool-bar 0.11.0 
git-control 0.8.2 
git-plus 5.25.4 
language-vue 0.21.2 
minimap 4.26.8 
nuclide 0.209.0 
platformio-ide-terminal 2.4.0 
tool-bar 1.0.1 
tree-view-git-status 1.3.1 
vim-mode 0.65.1 
```

**Comment by UziTech** [comment]
already fixed
