### ISSUE TITLE
in atom 1.12 the toolbar is not showing

### ISSUE THREAD

**Issue by unluisco** [cakecatz/flex-toolbar#90]
and even the command `Flex Tool Bar: Edit Config File` is not there

**Comment by samuelam** [comment]
Try running `apm build` from the command line. Or `apm-beta rebuild` if you're using the beta.

**Comment by mackelito** [comment]
Running that get me "Unrecognized command: build"

**Comment by mackelito** [comment]
New atom has a rebuild feature inside the editor.. running that gives:

```
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-electron-v1.3-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and electron@1.3.6 (electron-v1.3 ABI) (falling back to source compile with node-gyp) 
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "configure" "--fallback-to-build" "--module=/Users/markus/.atom/packages/flex-tool-bar/node_modules/fsevents/lib/binding/Release/electron-v1.3-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/markus/.atom/packages/flex-tool-bar/node_modules/fsevents/lib/binding/Release/electron-v1.3-darwin-x64"
gyp ERR! cwd /Users/markus/.atom/packages/flex-tool-bar/node_modules/fsevents
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp configure --fallback-to-build --module=/Users/markus/.atom/packages/flex-tool-bar/node_modules/fsevents/lib/binding/Release/electron-v1.3-darwin-x64/fse.node --module_name=fse --module_path=/Users/markus/.atom/packages/flex-tool-bar/node_modules/fsevents/lib/binding/Release/electron-v1.3-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/markus/.atom/packages/flex-tool-bar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 16.1.0
node-pre-gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/markus/.atom/packages/flex-tool-bar/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/markus/.atom/packages/flex-tool-bar/node_modules/fsevents
node-pre-gyp ERR! node -v v4.4.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok 

npm ERR! Darwin 16.1.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/markus/.atom/.apm/.apmrc" "--userconfig" "/Users/markus/.atom/.apmrc" "rebuild" "--runtime=electron" "--target=1.3.6" "--arch=x64"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.0.14 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/markus/.atom/packages/flex-tool-bar/npm-debug.log
```

**Comment by marshallbu** [comment]
Rebuilding from the incompatible packages screen worked for me.

I can concur that doing `apm build` from command line returns the same "Unrecognized command: build" for me as well.

**Comment by unluisco** [comment]
rebuild did the trick

**Comment by samuelam** [comment]
Sorry, that should have been `apm rebuild`, not `apm build`
